server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/User/Desktop/Lab4/ConfigService/src/main/resources/config


